config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users
  resources :admins, only: [:show, :edit, :update]
  resources :customers
  resources :training_videos
  resources :resources, except: :show

  get '/log_in' => 'user_sessions#new', as: :log_in
  post '/log_in' => 'user_sessions#create'
  delete '/log_out' => 'user_sessions#destroy', as: :log_out

  get '/log_in_admin' => 'admin_sessions#new', as: :log_in_admin
  post '/log_in_admin' => 'admin_sessions#create'
  delete '/log_out_admin' => 'admin_sessions#destroy', as: :log_out_admin

  get '/search_results' => 'search_results#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include PgSearch

  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, format: { with: /\A\d{5}\z/ }
  validates :phone, presence: true, format: { with: /\A\d{3}-\d{3}-\d{4}\z/ }
  validates :credit_score, presence: true, format: { with: /\A\d{3}\z/ }
  validates :tech_name, presence: true
  validates :package, presence: true
  validates :mmr, presence: true
  validates :date_sold, presence: true
  validates :date_installed, presence: true
  validates :user_id, presence: true

  mount_uploader :contract_ama, ContractAmaUploader
  mount_uploader :contract_sop, ContractSopUploader

  pg_search_scope :search_by_name, against: :name

  after_create do
    eft_stat = user.customers.where(eft: true).count * 100 / user.customers.count
    user.update_attribute(:eft_stat, eft_stat)
    sixty_month_stat = user.customers.where(sixty_month: true).count * 100 / user.customers.count
    user.update_attribute(:sixty_month_stat, sixty_month_stat)
    activation_stat = user.customers.where(activation: true).count * 100 / user.customers.count
    user.update_attribute(:activation_stat, activation_stat)
    takeover_stat = user.customers.where(takeover: true).count * 100 / user.customers.count
    user.update_attribute(:takeover_stat, takeover_stat)
    attrition = user.customers.where(canceled: true).count * 100 / user.customers.count
    user.update_attribute(:attrition, attrition)
    mmr_stat = user.customers.average(:mmr).round(2)
    user.update_attribute(:mmr_stat, mmr_stat)
    credit_score_stat = user.customers.average(:credit_score).round
    user.update_attribute(:credit_score_stat, credit_score_stat)
    basic_stat = user.customers.where(package: 'Basic').count * 100 / user.customers.count
    user.update_attribute(:basic_stat, basic_stat)
    basic_image_stat = user.customers.where(package: 'Basic Image').count * 100 / user.customers.count
    user.update_attribute(:basic_image_stat, basic_image_stat)
    go_green_stat = user.customers.where(package: 'Go Green').count * 100 / user.customers.count
    user.update_attribute(:go_green_stat, go_green_stat)
    basic_automation_stat = user.customers.where(package: 'Basic Automation').count * 100 / user.customers.count
    user.update_attribute(:basic_automation_stat, basic_automation_stat)
    automation_plus_stat = user.customers.where(package: 'Automation Plus').count * 100 / user.customers.count
    user.update_attribute(:automation_plus_stat, automation_plus_stat)
    fort_knox_stat = user.customers.where(package: 'Fort Knox').count * 100 / user.customers.count
    user.update_attribute(:fort_knox_stat, fort_knox_stat)
    sales_year = user.customers.where('extract(year from date_installed) = ?', Time.now.year).count
    user.update_attribute(:sales_year, sales_year)
    sales_month = user.customers.where('extract(month from date_installed) = ?', Time.now.month).count
    user.update_attribute(:sales_month, sales_month)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user, only: [:index, :show]
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:notice] = 'Customer created'
      redirect_to customers_url
    else
      flash[:alert] = 'Error creating customer'
      redirect_to new_customer_url
    end
  end

  def edit
  end

  def update
    if @customer.update_attributes(customer_params)
      flash[:notice] = 'Customer updated'
      redirect_to customer_url
    else
      flash[:alert] = 'Error updating customer'
      render :edit
    end
  end

  def destroy
    @customer.destroy
    flash[:notice] = 'Customer deleted'
    redirect_to customers_url
  end

  private

  def find_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :address, :city, :state, :zip,
    :phone, :credit_score, :tech_name, :package, :mmr, :date_sold,
    :date_installed, :sixty_month, :eft, :activation, :takeover, :canceled, :contract_ama, :contract_sop, :user_id)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/customers/edit.html.erb
<%= content_for :title, "Blackbriar - Edit #{@customer.name}" %>

<div class="row">
  <div class="small-12 columns">
    <h1 class="underline">Create Customer</h1>
  </div>
  <div class="small-12 medium-6 columns">

    <%= form_for @customer do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div>
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>

      <div>
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>

      <div>
        <%= f.label :state %>
        <%= f.select :state, options_for_select(us_states) %>
      </div>

      <div>
        <%= f.label :zip %>
        <%= f.text_field :zip %>
      </div>

      <div>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
      </div>

      <div>
        <%= f.label :credit_score %>
        <%= f.number_field :credit_score %>
      </div>

      <div>
        <%= f.label :package %>
        <%= f.select :package, options_for_select(['Basic', 'Basic Image', 'Go Green', 'Basic Automation', 'Automation Plus', 'Fort Knox']) %>
      </div>

      <div>
        <%= f.label :mmr %>
        <%= f.number_field :mmr, step: 'any' %>
      </div>

    </div>
    <div class="small-12 medium-6 columns">

      <div>
        <%= f.label :date_sold %>
        <%= f.date_field :date_sold %>
      </div>

      <div>
        <%= f.label :date_installed %>
        <%= f.date_field :date_installed %>
      </div>

      <div>
        <%= f.label :sixty_month %>
        <%= f.check_box :sixty_month %>
      </div>

      <div>
        <%= f.label :eft %>
        <%= f.check_box :eft %>
      </div>

      <div>
        <%= f.label :activation %>
        <%= f.check_box :activation %>
      </div>

      <div>
        <%= f.label :takeover %>
        <%= f.check_box :takeover %>
      </div>

      <div>
        <%= f.label :tech_name %>
        <%= f.text_field :tech_name %>
      </div>

      <div>
        <%= f.label :contract_ama %>
        <%= f.file_field :contract_ama %>
      </div>

      <div>
        <%= f.label :contract_sop %>
        <%= f.file_field :contract_sop %>
      </div>

      <div>
        <%= f.label :user_id %>
        <%= f.collection_select :user_id, User.all, :id, :name %>
      </div>

      <div>
        <%= f.label :canceled %>
        <%= f.check_box :canceled %>
      </div>

      <%= f.submit 'Update Customer', class: 'button' %>
    <% end %>
  </div>
</div>

app/views/customers/index.html.erb
<%= content_for :title, 'Blackbriar - Customers' %>

<div class="row">
  <div class="small-12 columns">
    <h1 class="underline">Customers</h1>
    <%= form_tag(search_results_path, method: :get) do %>

      <div>
        <%= search_field_tag :q %>
        <%= submit_tag 'Search', class: 'button' %>
      </div>

    <% end %>
    <dl>
      <% if Customer.count > 0 %>
        <% if current_user %>
          <% current_user.customers.each do |customer| %>
            <dt><%= link_to customer.name, customer_path(customer.id) %></dt>
            <dd>Installed On: <%= customer.date_installed %></dd>
          <% end %>
        <% else %>
          <% @customers.each do |customer| %>
            <dt><%= link_to customer.name, customer_path(customer.id) %></dt>
            <dd>Installed On: <%= customer.date_installed %></dd>
          <% end %>
        <% end %>
      <% end %>
    </dl>
  </div>
</div>

app/views/customers/new.html.erb
<%= content_for :title, 'Blackbriar - New Customer' %>

<div class="row">
  <div class="small-12 columns">
    <h1 class="underline">Create Customer</h1>
  </div>
  <div class="small-12 medium-6 columns">

    <%= form_for @customer do |f| %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div>
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>

      <div>
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>

      <div>
        <%= f.label :state %>
        <%= f.select :state, options_for_select(us_states) %>
      </div>

      <div>
        <%= f.label :zip %>
        <%= f.text_field :zip %>
      </div>

      <div>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
      </div>

      <div>
        <%= f.label :credit_score %>
        <%= f.number_field :credit_score %>
      </div>

      <div>
        <%= f.label :package %>
        <%= f.select :package, options_for_select(['Basic', 'Basic Image', 'Go Green', 'Basic Automation', 'Automation Plus', 'Fort Knox']) %>
      </div>

      <div>
        <%= f.label :mmr %>
        <%= f.number_field :mmr, step: 'any' %>
      </div>

    </div>
    <div class="small-12 medium-6 columns">

      <div>
        <%= f.label :date_sold %>
        <%= f.date_field :date_sold %>
      </div>

      <div>
        <%= f.label :date_installed %>
        <%= f.date_field :date_installed %>
      </div>

      <div>
        <%= f.label :sixty_month %>
        <%= f.check_box :sixty_month %>
      </div>

      <div>
        <%= f.label :eft %>
        <%= f.check_box :eft %>
      </div>

      <div>
        <%= f.label :activation %>
        <%= f.check_box :activation %>
      </div>

      <div>
        <%= f.label :takeover %>
        <%= f.check_box :takeover %>
      </div>

      <div>
        <%= f.label :tech_name %>
        <%= f.text_field :tech_name %>
      </div>

      <div>
        <%= f.label :contract_ama %>
        <%= f.file_field :contract_ama %>
      </div>

      <div>
        <%= f.label :contract_sop %>
        <%= f.file_field :contract_sop %>
      </div>

      <div>
        <%= f.label :user_id %>
        <%= f.collection_select :user_id, User.all, :id, :name %>
      </div>

      <%= f.submit 'Create Customer', class: 'button' %>
    <% end %>
  </div>
</div>

app/views/customers/show.html.erb
<%= content_for :title, "Blackbriar - #{@customer.name}" %>

<div class="row">
  <div class="small-12 columns">

    <h1 class="underline"><%= @customer.name %></h1>

  </div>
  <div class="small-12 medium-6 columns">

    <h4>Address</h4>
    <p><%= @customer.address %> <%= @customer.city %>, <%= @customer.state %> <%= @customer.zip %></p>

    <h4>Phone</h4>
    <p><%= @customer.phone %></p>

    <h4>Package</h4>
    <p><%= @customer.package %></p>

    <h4>MMR</h4>
    <p><%= @customer.mmr %></p>

    <h4>60 Month</h4>
    <p><%= @customer.sixty_month %></p>

    <h4>EFT</h4>
    <p><%= @customer.eft %></p>

    <h4>Activation</h4>
    <p><%= @customer.activation %></p>

  </div>
  <div class="small-12 medium-6 columns">

    <h4>Sold On</h4>
    <p><%= @customer.date_sold %></p>

    <h4>Installed On</h4>
    <p><%= @customer.date_installed %></p>

    <h4>Credit Score</h4>
    <p><%= @customer.credit_score %></p>

    <h4>Takeover</h4>
    <p><%= @customer.takeover %></p>

    <h4>Tech</h4>
    <p><%= @customer.tech_name %></p>

    <h4>Representative</h4>
    <p><%= User.find(@customer.user_id).name %></p>

    <h4>Canceled</h4>
    <p><%= @customer.canceled %></p>

    <h4>Contracts</h4>
    <%= image_tag @customer.contract_ama.url %>
    <%= image_tag @customer.contract_sop.url %>

    <% if current_admin %>
      <%= link_to 'Delete Customer', customer_path(@customer.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'button tiny alert'  %>
      <%= link_to 'Edit Customer', edit_customer_path(@customer.id), class: 'button tiny' %>
    <% end %>
  </div>
</div>