config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users
  resources :admins, only: [:show, :edit, :update]
  resources :customers
  resources :training_videos
  resources :resources, except: :show

  get '/log_in' => 'user_sessions#new', as: :log_in
  post '/log_in' => 'user_sessions#create'
  delete '/log_out' => 'user_sessions#destroy', as: :log_out

  get '/log_in_admin' => 'admin_sessions#new', as: :log_in_admin
  post '/log_in_admin' => 'admin_sessions#create'
  delete '/log_out_admin' => 'admin_sessions#destroy', as: :log_out_admin

  get '/search_results' => 'search_results#index'

end

app/views/resources/edit.html.erb
<%= content_for :title, 'Blackbriar - Edit Resource' %>

<div class="row">
  <div class="small-12 columns">
    <h1 class="underline">Edit Resource</h1>
    <%= form_for @resource do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :document %>
      <%= f.file_field :document %>
    </div>

    <%= f.submit 'Update Resource', class: 'button' %>
    <% end %>
  </div>
</div>

app/views/resources/index.html.erb
<%= content_for :title, 'Blackbriar - Resources' %>

<div class="row">
  <div class="small-12 columns">
    <h1 class="underline">Resources</h1>
    <% @resources.each do |resource| %>
      <h4><%= link_to "#{resource.title}", resource.document_url, target: '_blank' %></h4>
      <% if current_admin %>
        <%= link_to 'Delete Resource', resource_path(resource.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'button tiny alert'  %>
        <%= link_to 'Edit Resource', edit_resource_path(resource.id), class: 'button tiny' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/resources/new.html.erb
<%= content_for :title, 'Blackbriar - New Resource' %>

<div class="row">
  <div class="small-12 columns">
    <h1 class="underline">Create Resource</h1>
    <%= form_for @resource do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :document %>
      <%= f.file_field :document %>
    </div>

    <%= f.submit 'Create Resource', class: 'button' %>
    <% end %>
  </div>
</div>