config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users
  resources :admins, only: [:show, :edit, :update]
  resources :customers
  resources :training_videos
  resources :resources, except: :show

  get '/log_in' => 'user_sessions#new', as: :log_in
  post '/log_in' => 'user_sessions#create'
  delete '/log_out' => 'user_sessions#destroy', as: :log_out

  get '/log_in_admin' => 'admin_sessions#new', as: :log_in_admin
  post '/log_in_admin' => 'admin_sessions#create'
  delete '/log_out_admin' => 'admin_sessions#destroy', as: :log_out_admin

  get '/search_results' => 'search_results#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Blackbriar" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to 'Blackbriar Backend', root_path %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <% if current_user %>
            <li><%= link_to 'Customers', customers_path %></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Training Videos', training_videos_path %></li>
            <li><%= link_to 'Resources', resources_path %></li>
            <li><%= link_to 'Edit Account', edit_user_path(current_user) %></li>
            <li><%= link_to 'Log Out', log_out_path, method: :delete %></li>
          <% elsif current_admin %>
            <li><%= link_to 'Admin Profile', admin_path(current_admin) %></li>
            <li><%= link_to 'Create User', new_user_path %></li>
            <li><%= link_to 'Create Customer', new_customer_path %></li>
            <li><%= link_to 'Customers', customers_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Training Videos', training_videos_path %></li>
            <li><%= link_to 'Create Training Video', new_training_video_path %></li>
            <li><%= link_to 'Resources', resources_path %></li>
            <li><%= link_to 'Create Resource', new_resource_path %></li>
            <li><%= link_to 'Edit Account', edit_admin_path(current_admin) %></li>
            <li><%= link_to 'Log Out', log_out_admin_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Log In', log_in_path %></li>
            <li><%= link_to 'Admin Log In', log_in_admin_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>
    <div class="row">
      <div class="small-12 columns">
        <% if flash[:notice] %>
          <div class="label success flash-notice">
            <%= flash[:notice] %>
          </div>
        <% end %>

        <% if flash[:alert] %>
          <div class="label alert flash-alert">
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
    </div>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>